/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-15 09:38:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bishe.ecard.entity.user;
import java.util.List;
import org.apache.jasper.tagplugins.jstl.core.ForEach;

public final class card_005fmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" ");
 
String path=request.getContextPath();
String basePath=request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;
pageContext.setAttribute("basePath", basePath);


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<!--声明文档兼容模式，表示使用IE浏览器的最新模式-->\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<!--设置视口的宽度(值为设备的理想宽度)，页面初始缩放值<理想宽度/可见宽度>-->\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/shouye.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t\t<!-- 引入BootStrap核心js文件 -->\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/bootstrap.min.js\"></script>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.topfont{\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write("\t\t\t\tfont-size: 23px;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.swichbtn{\r\n");
      out.write("\t\t\t\tmargin-top: 20px;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.carduploadbtn{\r\n");
      out.write("\t\t\t\tmargin-left: 50px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.cardselect{\r\n");
      out.write("\t\t\t\twidth: 1000px;\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t    position: absolute;\r\n");
      out.write("\t\t\t    margin-left: 30px;\r\n");
      out.write("\t\t\t\tmargin-top: 20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.cardupload{\r\n");
      out.write("\t\t\t\twidth: 1000px;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tbackground-color: yellow;\r\n");
      out.write("\t\t\t\tposition: relative;\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t\tmargin-left: 30px;\r\n");
      out.write("\t\t\t\tmargin-top: 20px;\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.swichbtn{\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tdisplay:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.cardmanager{\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tdisplay:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.msg2{\r\n");
      out.write("\t\t\t\tmargin-top: 5px;\r\n");
      out.write("\t\t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write("\t\t\t\tfont-size: 15px;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\tmargin-left: 100px;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.delete{\r\n");
      out.write("\t\t\t\tmargin-left: 190px;\r\n");
      out.write("\t\t\t\tmargin-top: 10px;\t\r\n");
      out.write("\t\t\t\tfloat: left;\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttable{\r\n");
      out.write("\t\t\t\tmargin-left: 150px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tth{\r\n");
      out.write("\t\t\t\tpadding-left: 40px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttd{\r\n");
      out.write("\t\t\t\tpadding-left: 40px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.cardtable{\r\n");
      out.write("\t\t\t\tmargin-top: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.type1{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmargin-top: 5px;\r\n");
      out.write("\t\t\t\tmargin-left: 50px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.cardtype1btn{\r\n");
      out.write("\t\t\t\tmargin-left: 20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.cardtype2btn{\r\n");
      out.write("\t\t\t\tmargin-left: 20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.msg{\r\n");
      out.write("\t\t\t  font-size:20px;\r\n");
      out.write("\t\t\t  font-family: \"微软雅黑\";\r\n");
      out.write("\t\t\t  margin-left:50px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t");
 /* String param=request.getParameter("username"); 
	   request.setAttribute("username", param); */
	   Object user1=session.getAttribute("user");
	   Object user=request.getAttribute("user");
	   System.out.println("request----------"+user);
	   Cookie cookie[]=request.getCookies();
	   if(cookie!=null){
	   	 for(int i=0;i<cookie.length;i++){
	   		 Cookie c=cookie[i];
	   		 if(cookie[i].getName().equals("username")){
				  pageContext.setAttribute("username",c.getValue());	
				  System.out.println("usermanage+"+pageContext.getAttribute("username"));
		   		 }else{
		   			pageContext.setAttribute("username","");
		   			System.out.println("usermanage+"+pageContext.getAttribute("username"));
		   		 }
	   	 }	   	
	   }
      out.write("\r\n");
      out.write("\t\t<!--顶部模板管理-->\r\n");
      out.write("\t\t<div class=\"topfont\">\r\n");
      out.write("\t\t\t模板管理\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t <br>\r\n");
      out.write("\t\t <span class=\"msg\" id=\"msg\"></span>\r\n");
      out.write("\t\t<div class=\"swichbtn\" id=\"swichbtn\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"cardselectbtn\" id=\"cardselectbtn\">模板查询</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"carduploadbtn\" id=\"carduploadbtn\">模板上传</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"cardmanager\" class=\"cardmanager\">\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"cardselect\" id=\"cardselect\">\r\n");
      out.write("\t\t\t\t<div class=\"type1\" id=\"type1\">\r\n");
      out.write("\t\t\t\t\t<span>按模板类型查询:</span>\r\n");
      out.write("\t\t\t\t\t<select name=\"type\" id=\"selectType\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">请选择</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">贺卡</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">请帖</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t   \t\t \t<button type=\"button\" class=\"cardtype1btn\" id=\"cardtype1btn\">查询</button>\r\n");
      out.write("\t\t   \t\t \t<button type=\"button\" class=\"cardtype2btn\" id=\"cardtype2btn\">查询全部模板</button>\r\n");
      out.write("\t\t\t   </div>\r\n");
      out.write("\t\t\t\t<div class=\"delete\" id=\"delete\">\r\n");
      out.write("\t\t   \t\t \t<button type=\"button\" class=\"deletecard\" id=\"deletecard\">删除</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"msg2\">\r\n");
      out.write("\t\t\t\t   <span id=\"msg2\" class=\"msg2\"></span>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"cardtable\">\r\n");
      out.write("\t\t\t\t\t<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"cardtable\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>选择</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>序号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>模板图片</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>模板名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>模板类型</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>模板上传时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>模板使用次数</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"cardupload\" id=\"cardupload\">\r\n");
      out.write("\t\t\t\t123\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t//顶部按钮切换\r\n");
      out.write("\t\t\tvar cardselectbtn=document.getElementById('cardselectbtn');\r\n");
      out.write("\t\t\tvar carduploadbtn=document.getElementById('carduploadbtn');\r\n");
      out.write("\t\t\tvar cardselect=document.getElementById('cardselect');\r\n");
      out.write("\t\t\tvar cardupload=document.getElementById('cardupload');\r\n");
      out.write("\t\t\tcardselectbtn.onclick=function(){\r\n");
      out.write("\t\t\t\tcardselect.style.display='block';\r\n");
      out.write("\t\t\t\tcardupload.style.display='none';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcarduploadbtn.onclick=function(){\r\n");
      out.write("\t\t\t\tcardselect.style.display='none';\r\n");
      out.write("\t\t\t\tcardupload.style.display='block';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//判断用户是否登录是否有权限\r\n");
      out.write("\t\t\tvar username='");
      out.print(pageContext.getAttribute("username"));
      out.write("';\r\n");
      out.write("\t\t\tvar cardmanager=document.getElementById('cardmanager');\r\n");
      out.write("\t\t\tvar swichbtn=document.getElementById('swichbtn');\r\n");
      out.write("\t\t\tvar msg2=document.getElementById(\"msg2\");\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/selectstatus\",\r\n");
      out.write("\t\t\t\t\tasync:true,\r\n");
      out.write("\t\t\t\t\tdata:{\"username\":username},\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.msg=='1'){\r\n");
      out.write("\t\t\t\t\t\t\tmsg.style.color='red';\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tmsg.innerHTML=\"你不是管理员用户，无权操作!\";\r\n");
      out.write("\t\t\t\t\t\t}else if(data.msg=='0'){\r\n");
      out.write("\t\t\t\t\t\t\tcardmanager.style.display='block';\r\n");
      out.write("\t\t\t\t\t\t\tswichbtn.style.display='block';\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}else if(data.msg=='2'){\r\n");
      out.write("\t\t\t\t\t\t\tmsg.style.color='red';\t\t\r\n");
      out.write("\t\t\t\t\t\t\tmsg.innerHTML=\"请你先登录\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//按类型查询模板\t\r\n");
      out.write("\t\t\tvar msg=document.getElementById('msg');\r\n");
      out.write("\t\t\tvar  selectType=document.getElementById('selectType');\t\t\t\r\n");
      out.write("\t\t\tvar cardtype1btn=document.getElementById('cardtype1btn');\r\n");
      out.write("\t\t\tcardtype1btn.onclick=function(){\t\t\t\t\r\n");
      out.write("\t\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/selectcardType\",\r\n");
      out.write("\t\t\t\t\tasync:true,\r\n");
      out.write("\t\t\t\t\tdata:{\"type\":selectType.value},\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.msg=='0'){\r\n");
      out.write("\t\t\t\t\t\t  $(\"tbody\").detach();\r\n");
      out.write("\t\t\t\t\t\t  var res=data.cardmsg;\r\n");
      out.write("\t\t\t\t\t\t  msg2.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\t  var str='';\r\n");
      out.write("\t\t\t\t\t\t  $.each(res,function(index,result){\r\n");
      out.write("\t\t\t\t\t\t\t\t//console.log(index+result.userName);\r\n");
      out.write("\t\t\t\t\t\t\t\tstr='<td><input type=\"checkbox\" name=\"cardname\" id=\"cardname\" value=\"'+result.cardId+'\">'+'</td>'+'<td>'+result.cardId+'</td>'+'<td><img width=\"50px\" height=\"40px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/'+result.cardPath+'\"/>'+'</td>'+'<td>'+result.cardName+'</td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\t'<td>'+result.cardType+'</td>'+'<td>'+result.cardTime+'</td>'+'<td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\tresult.cardCount+'</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#cardtable\").append('<tbody><tr>'+str+'</tr><tbody>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t}else if(data.msg=='1'){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"tbody\").detach();\r\n");
      out.write("\t\t\t\t\t\t\t msg2.innerHTML=\"请选择贺卡或者请帖\";\r\n");
      out.write("\t\t\t\t\t\t\t msg2.style.color='red';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//查询全部模板\r\n");
      out.write("\t\t\tvar cardtype2btn=document.getElementById('cardtype2btn');\r\n");
      out.write("\t\t\tcardtype2btn.onclick=function(){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/selectcardAll\",\r\n");
      out.write("\t\t\t\t\tasync:true,\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.msg=='0'){\r\n");
      out.write("\t\t\t\t\t\t  $(\"tbody\").detach();\r\n");
      out.write("\t\t\t\t\t\t  var res=data.cardmsg;\r\n");
      out.write("\t\t\t\t\t\t  msg2.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\t  var str='';\r\n");
      out.write("\t\t\t\t\t\t  $.each(res,function(index,result){\r\n");
      out.write("\t\t\t\t\t\t\t\t//console.log(index+result.userName);\r\n");
      out.write("\t\t\t\t\t\t\t\tstr='<td><input type=\"checkbox\" name=\"cardname\" id=\"cardname\" value=\"'+result.cardId+'\">'+'</td>'+'<td>'+result.cardId+'</td>'+'<td><img width=\"50px\" height=\"40px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/'+result.cardPath+'\"/>'+'</td>'+'<td>'+result.cardName+'</td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\t'<td>'+result.cardType+'</td>'+'<td>'+result.cardTime+'</td>'+'<td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\tresult.cardCount+'</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#cardtable\").append('<tbody><tr>'+str+'</tr><tbody>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar checkBoxValue=new Array();\r\n");
      out.write("\t\t\tfunction getChexBoxValue(){\r\n");
      out.write("\t\t\t\tvar test=$(\"input[name='cardname']:checked\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttest.each(function(index){\r\n");
      out.write("\t\t\t\t\tcheckBoxValue[index]=$(this).val();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t//checkBoxValue=checkBoxValue.substring(0,checkBoxValue.length-1);\r\n");
      out.write("\t\t\t\tconsole.log(checkBoxValue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar deletecard=document.getElementById(\"deletecard\");\r\n");
      out.write("\t\t\tdeletecard.onclick=function(){\r\n");
      out.write("\t\t\t\tgetChexBoxValue();\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/deletecard',\r\n");
      out.write("\t\t\t\t\taysnc:true,\r\n");
      out.write("\t\t\t\t\tdata:{\"cardcke\":checkBoxValue},\r\n");
      out.write("\t\t\t\t\ttraditional : true,\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.msg=='0'){\r\n");
      out.write("\t\t\t\t\t\t  $(\"tbody\").detach();\r\n");
      out.write("\t\t\t\t\t\t  var res=data.cardmsg;\r\n");
      out.write("\t\t\t\t\t\t  msg2.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\t  var str='';\r\n");
      out.write("\t\t\t\t\t\t  $.each(res,function(index,result){\r\n");
      out.write("\t\t\t\t\t\t\t\t//console.log(index+result.userName);\r\n");
      out.write("\t\t\t\t\t\t\t\tstr='<td><input type=\"checkbox\" name=\"cardname\" id=\"cardname\" value=\"'+result.cardId+'\">'+'</td>'+'<td>'+result.cardId+'</td>'+'<td><img width=\"50px\" height=\"40px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/'+result.cardPath+'\"/>'+'</td>'+'<td>'+result.cardName+'</td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\t'<td>'+result.cardType+'</td>'+'<td>'+result.cardTime+'</td>'+'<td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\tresult.cardCount+'</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#cardtable\").append('<tbody><tr>'+str+'</tr><tbody>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
