/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-12 12:03:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
String path=request.getContextPath();
String basePath=request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;
pageContext.setAttribute("basePath", basePath);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<!--声明文档兼容模式，表示使用IE浏览器的最新模式-->\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<!--设置视口的宽度(值为设备的理想宽度)，页面初始缩放值<理想宽度/可见宽度>-->\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<title>登录</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/login.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/bootstrap.min.css\" />\r\n");
      out.write("\t   <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-3.4.1.min.js\" ></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/bootstrap.min.js\" ></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!--头部-->\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"loginwindow\">\r\n");
      out.write("\t\t\t\t<div class=\"loginlabel\">\r\n");
      out.write("\t\t\t\t\t登&nbsp;录\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"formdiv\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" id=\"form\" action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t   <label  class=\"col-sm-4 control-label fontset\">用户名:</label>\r\n");
      out.write("\t\t\t\t  <div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t     <input type=\"text\" class=\"form-control\" name=\"username\" id=\"username\" placeholder=\"请输入用户名\">   \r\n");
      out.write("\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label  class=\"col-sm-4 control-label fontset\">密码:</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t      <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" placeholder=\"请输入密码\">\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t   <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-2 msg\">\r\n");
      out.write("\t\t\t\t      <span  id=\"msg\"></span>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group btnf\">\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t\t      <button type=\"button\" class=\"btn btn-default btnset\"  id=\"loginbtn\">登录</button>\r\n");
      out.write("\t\t\t\t     <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/registerpage\"><button type=\"button\" class=\"btn btn-default btnset\" id=\"registerbtn\" >注册</button></a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t <script>\r\n");
      out.write("\t \tvar userval=document.getElementById('username');\r\n");
      out.write("\t \tvar passval=document.getElementById('password');\r\n");
      out.write("\t \tvar loginbtn=document.getElementById('loginbtn');\r\n");
      out.write("\t \tvar msg=document.getElementById('msg');\r\n");
      out.write("\t \tloginbtn.onclick=function(){\t \t\t\r\n");
      out.write("//\t \t\ttype:\"post\",\r\n");
      out.write("//\t\t\t\t\turl:\"http://localhost:8080/ecard/sendmsg\",\r\n");
      out.write("//\t\t\t\t\tasync:true,\r\n");
      out.write("//\t\t\t\t\tdata:$(\"#form1\").serialize(),\r\n");
      out.write("//\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("//\t\t\t\t\t\talert(\"成功\")\r\n");
      out.write("//\t\t\t\t\t}\r\n");
      out.write("         if(userval.value==''||passval.value==''){\r\n");
      out.write("         \tmsg.style.color='red';\r\n");
      out.write("         \tmsg.innerHTML='请输入用户名或密码';\r\n");
      out.write("         }else if(userval.value!=''&&passval.value!=''){\r\n");
      out.write("         \tmsg.innerHTML='';\r\n");
      out.write("\t \t\t$.ajax({\r\n");
      out.write("\t \t\ttype:\"post\",\r\n");
      out.write("\t \t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login\",\r\n");
      out.write("\t \t\tasync:true,\r\n");
      out.write("\t \t\tdata:$('#form').serialize(),\r\n");
      out.write("\t \t\tsuccess:function(data){\r\n");
      out.write("\t \t\t\tif(data.msg=='1'){\r\n");
      out.write("\t \t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t \t\t\t\tmsg.innerHTML='用户名或密码错误';\r\n");
      out.write("\t \t\t\t}else{\r\n");
      out.write("\t \t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/index\";\r\n");
      out.write("\t \t\t\t}\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t \t)};\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \t \r\n");
      out.write("\t  \r\n");
      out.write("\t </script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
