/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-13 02:07:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.ForEach;

public final class user_005fcenter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" ");
 
String path=request.getContextPath();
String basePath=request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;
pageContext.setAttribute("basePath", basePath);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.user_center{\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tmargin: 10px;\r\n");
      out.write("\t\t\t\tpadding-top: 40px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.usermsg{\t\t\t\t\r\n");
      out.write("\t\t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write("\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.set{\r\n");
      out.write("\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.btn_user{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t\tbackground-color: antiquewhite;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\tborder: 1px solid;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t");
 /* String param=request.getParameter("username"); 
	   request.setAttribute("username", param); */
	   Cookie cookie[]=request.getCookies();
	   if(cookie!=null){
	   	 for(int i=0;i<cookie.length;i++){
	   		 Cookie c=cookie[i];
	   		 if(cookie[i].getName().equals("username")){
				  pageContext.setAttribute("username",c.getValue());	
				  System.out.println("usercenter+"+pageContext.getAttribute("username"));
		   		 }else{
		   			pageContext.setAttribute("username","");
		   			System.out.println("usercenter+"+pageContext.getAttribute("username"));
		   		 }
	   	 }	   	
	   }
      out.write("\r\n");
      out.write("\t\t<div class=\"user_center\">\t\t\t\t\t\r\n");
      out.write("\t\t<span class=\"usermsg\">个人信息修改");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span><br /><br /><br /><br />\r\n");
      out.write("\t\t<form action=\"#\" method=\"post\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<span class=\"password set\">新密码:</span>&nbsp;&nbsp;&nbsp;<input type=\"password\" id=\"password\" name=\"password\" maxlength=\"10\"  value=\"\"/><br /><br />\r\n");
      out.write("\t\t\t<span class=\"password set\">确认密码:</span>&nbsp;&nbsp;&nbsp;<input type=\"password\" id=\"commitpassword\" name=\"password\" maxlength=\"10\" value=\"\"/><br /><br />\r\n");
      out.write("\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t<span class=\"msg\" id=\"msg\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"确认\" class=\"btn_user\" id=\"btn_user\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar userpass=document.getElementById('password');\r\n");
      out.write("\t\t\tvar commitpassword=document.getElementById('commitpassword');\r\n");
      out.write("\t\t\tvar btn_user=document.getElementById('btn_user');\r\n");
      out.write("\t\t\tvar msg=document.getElementById('msg')\r\n");
      out.write("\t\t\tvar reg=/^[A-Za-z0-9]+$/;\r\n");
      out.write("\t\t\tvar userstatus=false;\r\n");
      out.write("\t\t\tvar commistuserstatus=false;\r\n");
      out.write("\t\t    function valitad(){\r\n");
      out.write("\t\t\tuserpass.onblur=function(){\r\n");
      out.write("\t\t\tif(userpass.value==''){\r\n");
      out.write("\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\tmsg.innerHTML='密码不能为空';\r\n");
      out.write("\t\t\t\tuserstatus=false;\r\n");
      out.write("\t\t\t}else if(!reg.test(userpass.value)){\r\n");
      out.write("\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\tmsg.innerHTML='字母和数字组合';\r\n");
      out.write("\t\t\t\tuserstatus=false;\r\n");
      out.write("\t\t\t}else if(userpass.value<3||userpass.value>10){\r\n");
      out.write("\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\tmsg.innerHTML='密码长度3-10位';\r\n");
      out.write("\t\t\t\tuserstatus=false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tmsg.innerHTML='';\r\n");
      out.write("\t\t\t\tuserstatus=true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcommitpassword.onblur=function(){\r\n");
      out.write("\t\t\tif(commitpassword.value==''){\r\n");
      out.write("\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\tmsg.innerHTML='密码不能为空';\r\n");
      out.write("\t\t\t\tcommistuserstatus=false;\r\n");
      out.write("\t\t\t}else if(!reg.test(commitpassword.value)){\r\n");
      out.write("\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\tmsg.innerHTML='字母和数字组合';\r\n");
      out.write("\t\t\t\tcommistuserstatus=false;\r\n");
      out.write("\t\t\t}else if(commitpassword.value<3||commitpassword.value>10){\r\n");
      out.write("\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\tmsg.innerHTML='密码长度3-10位';\r\n");
      out.write("\t\t\t\tcommistuserstatus=false;\r\n");
      out.write("\t\t\t}else if(commitpassword.value!=userpass.value){\r\n");
      out.write("\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\tmsg.innerHTML='两次密码输入不一样';\r\n");
      out.write("\t\t\t\tcommistuserstatus=false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tmsg.innerHTML='';\r\n");
      out.write("\t\t\t\tcommistuserstatus=true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\tvar username='");
      out.print(pageContext.getAttribute("username") );
      out.write("';\r\n");
      out.write("\t\t\tconsole.log(username);\r\n");
      out.write("\t\t\tbtn_user.onclick=function(){\r\n");
      out.write("\t\t\t\tvalitad();\r\n");
      out.write("\t\t\t\tif(userstatus==false||commistuserstatus==false){\r\n");
      out.write("\t\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\t\tmsg.innerHTML=\"请正确输入密码\";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/updatepass\",\r\n");
      out.write("\t\t\t\t\t\tasync:true,\r\n");
      out.write("\t\t\t\t\t\tdata:{\"username\":username,\"userpass\":userpass.value},\r\n");
      out.write("\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\tif(data.msg=='0'){\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"密码修改成功\");\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/loginpage\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
