/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-15 09:33:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bishe.ecard.entity.user;
import java.util.List;
import org.apache.jasper.tagplugins.jstl.core.ForEach;

public final class user_005fmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");
 
String path=request.getContextPath();
String basePath=request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;
pageContext.setAttribute("basePath", basePath);


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<!--声明文档兼容模式，表示使用IE浏览器的最新模式-->\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<!--设置视口的宽度(值为设备的理想宽度)，页面初始缩放值<理想宽度/可见宽度>-->\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/shouye.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t\t<!-- 引入BootStrap核心js文件 -->\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/bootstrap.min.js\"></script>\t\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t.usermanager{\r\n");
      out.write("\t\t\t\theight: 500px;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tmargin-left: 200px;\r\n");
      out.write("\t\t\t\tmargin-top: 20px;\r\n");
      out.write("\t\t\t\tmargin-right: 200px;\t\t\t\t\r\n");
      out.write("\t\t\t\tfont-size: 16px;\r\n");
      out.write("\t\t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t.tableuser{\t\t\t\r\n");
      out.write("\t\t\t    text-algin:center;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t.usertr{\r\n");
      out.write("\t\t\t\tmargin-left: 20px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t.tatle{\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write("\t\t\t\tfont-size: 23px;\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\ttd{\t\t\t\t\r\n");
      out.write("\t\t\t    padding-left:10px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tth{\r\n");
      out.write("\t\t\t  padding-left:10px;\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.selectuser{\r\n");
      out.write("\t\t\t\tmargin-top: 20px;\r\n");
      out.write("\t\t\t\theight: 30px;\t\t\t\t\r\n");
      out.write("\t\t\t\tmargin-left: 200px;\r\n");
      out.write("\t\t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.msg{\r\n");
      out.write("\t\t\t\tmargin-left: 30px;\r\n");
      out.write("\t\t\t\tmargin-top: 10px;\r\n");
      out.write("\t\t\t\tfont-size:20px;\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.msg{\r\n");
      out.write("\t\t\t   float:left;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.delete{\r\n");
      out.write("\t\t\t float:left;\r\n");
      out.write("\t\t\t margin-left:200px;\r\n");
      out.write("\t\t\t margin-top:30px;\r\n");
      out.write("\t\t\t display:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 /* String param=request.getParameter("username"); 
	   request.setAttribute("username", param); */
	   Object user1=session.getAttribute("user");
	   Object user=request.getAttribute("user");
	   System.out.println("request----------"+user);
	   Cookie cookie[]=request.getCookies();
	   if(cookie!=null){
	   	 for(int i=0;i<cookie.length;i++){
	   		 Cookie c=cookie[i];
	   		 if(cookie[i].getName().equals("username")){
				  pageContext.setAttribute("username",c.getValue());	
				  System.out.println("usermanage+"+pageContext.getAttribute("username"));
		   		 }else{
		   			pageContext.setAttribute("username","");
		   			System.out.println("usermanage+"+pageContext.getAttribute("username"));
		   		 }
	   	 }	   	
	   }
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("\t\t<div class=\"tatle\">\r\n");
      out.write("\t\t\t用户管理中心\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"selectuser\" id=\"selectuser\">\r\n");
      out.write("\t\t\t<span class=\"\">按用户名查询：</span>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"username\" id=\"username\" value=\"\" />&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"selectusername-btn\" id=\"selectusername_btn\">查询信息</button>&nbsp;&nbsp;\r\n");
      out.write("\t\t    <button type=\"button\" class=\"select-btn\" id=\"select_btn\">查询全部用户信息</button><br />\r\n");
      out.write("\t\t  \t    \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"delete\" id=\"delete\">\r\n");
      out.write("\t\t    <button type=\"button\" class=\"deleteuser\" id=\"deleteuser\">删除</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"msg\">\r\n");
      out.write("\t\t\t  <span class=\"msg\" id=\"msg\"></span>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t<div class=\"usermanager\" id=\"usermanager\">\r\n");
      out.write("\t\t\t<table id=\"tableuser\"   algin=\"center\"  cellpadding=\"0\" cellspacing=\"0\"> \r\n");
      out.write("\t\t\t  <thead>\t\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t<th>选择</th>\r\n");
      out.write("\t\t\t\t\t<th>序号</th>\r\n");
      out.write("\t\t\t\t\t<th>用户名</th>\r\n");
      out.write("\t\t\t\t\t<th>邮箱</th>\r\n");
      out.write("\t\t\t\t\t<th>注册时间</th>\r\n");
      out.write("\t\t\t\t\t<th>登录时间</th>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody></tbody>\t\t   \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t//获取cookie中的值 查询状态为1是普通用户，只给msg中显示你不是管理员\r\n");
      out.write("\t//查询是0则为管理员   显示用户信息的界面\t\t\t\r\n");
      out.write("\t\t\tvar username='");
      out.print(pageContext.getAttribute("username"));
      out.write("';\r\n");
      out.write("\t\t\tconsole.log(username+\"--------\");\r\n");
      out.write("\t\t\tvar msg=document.getElementById('msg');\r\n");
      out.write("\t\t\tvar selectuser=document.getElementById('selectuser');\r\n");
      out.write("\t\t\tvar usermanager=document.getElementById('usermanager');\r\n");
      out.write("\t\t\tvar deleteu=document.getElementById(\"delete\");\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/selectstatus\",\r\n");
      out.write("\t\t\t\t\tasync:true,\r\n");
      out.write("\t\t\t\t\tdata:{\"username\":username},\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.msg=='1'){\r\n");
      out.write("\t\t\t\t\t\t\tmsg.style.color='red';\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tmsg.innerHTML=\"你不是管理员用户，无权操作!\";\r\n");
      out.write("\t\t\t\t\t\t}else if(data.msg=='0'){\r\n");
      out.write("\t\t\t\t\t\t\tselectuser.style.display='block';\r\n");
      out.write("\t\t\t\t\t\t\tusermanager.style.display='block';\r\n");
      out.write("\t\t\t\t\t\t\tdeleteu.style.display='block';\r\n");
      out.write("\t\t\t\t\t\t}else if(data.msg=='2'){\r\n");
      out.write("\t\t\t\t\t\t\tmsg.style.color='red';\t\t\r\n");
      out.write("\t\t\t\t\t\t\tmsg.innerHTML=\"请你先登录\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t\t});\t\t\t\t\t\r\n");
      out.write("\t\t\t//后台获取数据添加到表格\r\n");
      out.write("\t\t\tvar selectusername_btn=document.getElementById(\"selectusername_btn\");\r\n");
      out.write("\t\t\tvar usernameselect=document.getElementById('username');\r\n");
      out.write("\t\t\tvar select_btn=document.getElementById('select_btn');\r\n");
      out.write("\t\t\tselectusername_btn.onclick=function(){\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/userselect\",\r\n");
      out.write("\t\t\t\t\tasync:true,\r\n");
      out.write("\t\t\t\t\tdata:{'username':usernameselect.value},\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.msg=='1'){\r\n");
      out.write("\t\t\t\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\t\t\t\tmsg.innerHTML=\"没有查询到\"+usernameselect.value+\"相关信息\";\r\n");
      out.write("\t\t\t\t\t\t\t$(\"tbody\").detach();//删除节点的\r\n");
      out.write("\t\t\t\t\t\t}else{\t\t\r\n");
      out.write("\t\t\t\t\t      //console.log(data.usermsg[0].userId);\r\n");
      out.write("\t\t\t\t\t      $(\"tbody\").detach();\r\n");
      out.write("\t\t\t\t\t\t\tvar res=data.usermsg;\r\n");
      out.write("\t\t\t\t\t\t    msg.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(res);\r\n");
      out.write("\t\t\t\t\t\t\tvar str='';\r\n");
      out.write("\t\t\t\t\t\t\t//var sthead='<thead>\t<tr ><th>序号</th><th>用户名</th><th>邮箱</th><th>注册时间</th><th>登录时间</th><th colspan=\"2\">操作</th></tr></thead>'\r\n");
      out.write("\t\t\t\t\t\t\t$.each(res,function(index,result){\r\n");
      out.write("\t\t\t\t\t\t\t\t//console.log(index+result.userName);\r\n");
      out.write("\t\t\t\t\t\t\t\tstr='<td>'+1+'</td>'+'<td>'+result.userId+'</td>'+'<td>'+result.userName+'</td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\t'<td>'+result.email+'</td>'+'<td>'+result.registerTime+'</td>'+'<td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\tresult.loginTime+'</td>'+'<td>'+'</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#tableuser\").append('<tbody><tr>'+str+'</tr><tbody>');\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar flag=false;\r\n");
      out.write("\t\t\tselect_btn.onclick=function(){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/userSelectAll\",\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\taysnc:true,\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.msg=='1'){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"tbody\").detach();\r\n");
      out.write("\t\t\t\t\t\t\tvar res=data.usermsg;\r\n");
      out.write("\t\t\t\t\t\t\tmsg.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tvar str=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t$.each(res,function(index,result){\r\n");
      out.write("\t\t\t\t\t\t\t\t//console.log(index+result.userName);\r\n");
      out.write("\t\t\t\t\t\t\t\tstr='<td><input type=\"checkbox\" name=\"username\" id=\"username\" value=\"'+result.userName+'\">'+'</td>'+'<td>'+result.userId+'</td>'+'<td>'+result.userName+'</td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\t'<td>'+result.email+'</td>'+'<td>'+result.registerTime+'</td>'+'<td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\tresult.loginTime+'</td>'+'<td>'+'</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#tableuser\").append('<tbody><tr>'+str+'</tr><tbody>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}else if(data.msg=='0'){\r\n");
      out.write("\t\t\t\t\t\t\tmsg.innerHTML=\"未查询到数据\";\r\n");
      out.write("\t\t\t\t\t\t\tmsg.style.color='red';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar checkBoxValue=new Array();\r\n");
      out.write("\t\t\tfunction getChexBoxValue(){\r\n");
      out.write("\t\t\t\tvar test=$(\"input[name='username']:checked\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttest.each(function(index){\r\n");
      out.write("\t\t\t\t\tcheckBoxValue[index]=$(this).val();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t//checkBoxValue=checkBoxValue.substring(0,checkBoxValue.length-1);\r\n");
      out.write("\t\t\t\tconsole.log(checkBoxValue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar deleteuser=document.getElementById(\"deleteuser\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdeleteuser.onclick=function(){\r\n");
      out.write("\t\t\t\t   getChexBoxValue();\r\n");
      out.write("\t\t\t\t    $.ajax({\r\n");
      out.write("\t\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/deleteuser',\r\n");
      out.write("\t\t\t\t\taysnc:true,\r\n");
      out.write("\t\t\t\t\tdata:{\"usercke\":checkBoxValue},\r\n");
      out.write("\t\t\t\t\ttraditional : true,\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.msg=='1'){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"tbody\").detach();\r\n");
      out.write("\t\t\t\t\t\t\tvar res=data.usermsg;\r\n");
      out.write("\t\t\t\t\t\t\tmsg.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tvar str=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t$.each(res,function(index,result){\r\n");
      out.write("\t\t\t\t\t\t\t\t//console.log(index+result.userName);\r\n");
      out.write("\t\t\t\t\t\t\t\tstr='<td><input type=\"checkbox\" name=\"username\" id=\"username\" value=\"'+result.userName+'\">'+'</td>'+'<td>'+result.userId+'</td>'+'<td>'+result.userName+'</td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\t'<td>'+result.email+'</td>'+'<td>'+result.registerTime+'</td>'+'<td>'+\r\n");
      out.write("\t\t\t\t\t\t\t\tresult.loginTime+'</td>'+'<td>'+'</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#tableuser\").append('<tbody><tr>'+str+'</tr><tbody>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
